"""
This package includes some usefull fucntions that are used for logging and 
formatting the artifacts generated by different executions.
"""

from .utils import *
from .log import *
from .setup import *
from .results import *

